// <auto-generated>
// Generated by scripts/generate_bridge_registry.py from configs/plant_registry.json.
// Runtime CardUI metadata remains authoritative; these values are fallbacks only.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Globalization;

namespace PvZRLBridge;

internal sealed class GeneratedPlantMetadata
{
    public GeneratedPlantMetadata(
        int plantTypeId,
        string canonicalName,
        IReadOnlyList<string> aliases,
        int fallbackCost,
        float fallbackCooldownSeconds,
        string category,
        string role,
        bool enabledForTraining,
        bool bridgeFallbackEnabled)
    {
        PlantTypeId = plantTypeId;
        CanonicalName = canonicalName;
        Aliases = aliases;
        FallbackCost = fallbackCost;
        FallbackCooldownSeconds = fallbackCooldownSeconds;
        Category = category;
        Role = role;
        EnabledForTraining = enabledForTraining;
        BridgeFallbackEnabled = bridgeFallbackEnabled;
    }

    public int PlantTypeId { get; }
    public string CanonicalName { get; }
    public IReadOnlyList<string> Aliases { get; }
    public int FallbackCost { get; }
    public float FallbackCooldownSeconds { get; }
    public string Category { get; }
    public string Role { get; }
    public bool EnabledForTraining { get; }
    public bool BridgeFallbackEnabled { get; }
}

internal static class GeneratedPlantRegistry
{
    public const string SourceSha256 = "608c3064b836f4a219e765c07480763e84dd413c3f84075390b63196f5e8c7b2";

    private static readonly IReadOnlyDictionary<int, GeneratedPlantMetadata> ById =
        new Dictionary<int, GeneratedPlantMetadata>
        {
            [0] = new GeneratedPlantMetadata(
                plantTypeId: 0,
                canonicalName: "Peashooter",
                aliases: new[] { "Pea Shooter", "Pea" },
                fallbackCost: 100,
                fallbackCooldownSeconds: 7.5f,
                category: "attacker",
                role: "attacker",
                enabledForTraining: true,
                bridgeFallbackEnabled: true),
            [1] = new GeneratedPlantMetadata(
                plantTypeId: 1,
                canonicalName: "SunFlower",
                aliases: new[] { "Sunflower", "Sun Flower", "sun", "economy" },
                fallbackCost: 50,
                fallbackCooldownSeconds: 7.5f,
                category: "economy",
                role: "economy",
                enabledForTraining: true,
                bridgeFallbackEnabled: true),
            [2] = new GeneratedPlantMetadata(
                plantTypeId: 2,
                canonicalName: "CherryBomb",
                aliases: new[] { "Cherry Bomb", "Cherry" },
                fallbackCost: 150,
                fallbackCooldownSeconds: 50.0f,
                category: "explosive",
                role: "explosive",
                enabledForTraining: false,
                bridgeFallbackEnabled: false),
            [3] = new GeneratedPlantMetadata(
                plantTypeId: 3,
                canonicalName: "WallNut",
                aliases: new[] { "Wall-Nut", "Wallnut", "Nut" },
                fallbackCost: 50,
                fallbackCooldownSeconds: 30.0f,
                category: "blocker",
                role: "blocker",
                enabledForTraining: false,
                bridgeFallbackEnabled: false),
            [4] = new GeneratedPlantMetadata(
                plantTypeId: 4,
                canonicalName: "PotatoMine",
                aliases: new[] { "Potato Mine", "Potato", "Mine" },
                fallbackCost: 25,
                fallbackCooldownSeconds: 30.0f,
                category: "explosive",
                role: "explosive",
                enabledForTraining: true,
                bridgeFallbackEnabled: false),
            [5] = new GeneratedPlantMetadata(
                plantTypeId: 5,
                canonicalName: "SnowPea",
                aliases: new[] { "Snow Pea" },
                fallbackCost: 175,
                fallbackCooldownSeconds: 7.5f,
                category: "support",
                role: "support",
                enabledForTraining: true,
                bridgeFallbackEnabled: false),
            [6] = new GeneratedPlantMetadata(
                plantTypeId: 6,
                canonicalName: "Chomper",
                aliases: new[] { "Chomp" },
                fallbackCost: 150,
                fallbackCooldownSeconds: 7.5f,
                category: "attacker",
                role: "attacker",
                enabledForTraining: true,
                bridgeFallbackEnabled: false),
            [7] = new GeneratedPlantMetadata(
                plantTypeId: 7,
                canonicalName: "Repeater",
                aliases: new[] { "Repeater Seed" },
                fallbackCost: 200,
                fallbackCooldownSeconds: 7.5f,
                category: "attacker",
                role: "attacker",
                enabledForTraining: true,
                bridgeFallbackEnabled: false),
            [8] = new GeneratedPlantMetadata(
                plantTypeId: 8,
                canonicalName: "PuffShroom",
                aliases: new[] { "Puff-shroom", "Puff Shroom" },
                fallbackCost: 0,
                fallbackCooldownSeconds: 7.5f,
                category: "attacker",
                role: "attacker",
                enabledForTraining: true,
                bridgeFallbackEnabled: false),
            [9] = new GeneratedPlantMetadata(
                plantTypeId: 9,
                canonicalName: "SunShroom",
                aliases: new[] { "Sun-shroom", "Sun Shroom" },
                fallbackCost: 25,
                fallbackCooldownSeconds: 7.5f,
                category: "economy",
                role: "economy",
                enabledForTraining: true,
                bridgeFallbackEnabled: false),
            [10] = new GeneratedPlantMetadata(
                plantTypeId: 10,
                canonicalName: "FumeShroom",
                aliases: new[] { "Fume-shroom", "Fume Shroom" },
                fallbackCost: 75,
                fallbackCooldownSeconds: 7.5f,
                category: "attacker",
                role: "attacker",
                enabledForTraining: true,
                bridgeFallbackEnabled: false),
            [11] = new GeneratedPlantMetadata(
                plantTypeId: 11,
                canonicalName: "GraveBuster",
                aliases: new[] { "Grave Buster" },
                fallbackCost: 75,
                fallbackCooldownSeconds: 7.5f,
                category: "utility",
                role: "utility",
                enabledForTraining: true,
                bridgeFallbackEnabled: false),
        };

    public static int Count => ById.Count;

    public static bool TryGet(int plantTypeId, out GeneratedPlantMetadata metadata)
    {
        if (ById.TryGetValue(plantTypeId, out var resolved))
        {
            metadata = resolved;
            return true;
        }

        metadata = null!;
        return false;
    }

    public static bool TryGetBridgeFallbackCost(int plantTypeId, out int cost)
    {
        if (TryGet(plantTypeId, out var metadata) && metadata.BridgeFallbackEnabled)
        {
            cost = metadata.FallbackCost;
            return true;
        }

        cost = 0;
        return false;
    }

    public static string ResolveCanonicalNameFallback(int plantTypeId, string runtimeName)
    {
        var numericName = plantTypeId.ToString(CultureInfo.InvariantCulture);
        if (!string.IsNullOrWhiteSpace(runtimeName) &&
            !string.Equals(runtimeName, numericName, StringComparison.Ordinal))
        {
            return runtimeName;
        }

        return TryGet(plantTypeId, out var metadata) ? metadata.CanonicalName : runtimeName;
    }
}
