"""Generate deterministic C# fallback metadata from the canonical registry."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Iterable


ROOT = Path(__file__).resolve().parents[1]
PYTHON_DIR = ROOT / "python"
if str(PYTHON_DIR) not in sys.path:
    sys.path.insert(0, str(PYTHON_DIR))

from pvzrl_registry import (  # noqa: E402
    DEFAULT_PLANT_REGISTRY_PATH,
    PlantDefinition,
    PlantRegistry,
    get_plant_registry,
    normalize_plant_name,
)


DEFAULT_OUTPUT_PATH = ROOT / "src" / "PvZRLBridge" / "GeneratedPlantRegistry.cs"


def _csharp_string(value: str) -> str:
    return json.dumps(str(value), ensure_ascii=True)


def _csharp_float(value: float) -> str:
    text = format(float(value), ".15g")
    if "." not in text and "e" not in text.lower():
        text += ".0"
    return text + "f"


def _render_aliases(values: Iterable[str]) -> str:
    aliases = ", ".join(_csharp_string(value) for value in values)
    return f"new[] {{ {aliases} }}" if aliases else "Array.Empty<string>()"


def _render_entry(definition: PlantDefinition) -> list[str]:
    return [
        f"            [{definition.plant_type_id}] = new GeneratedPlantMetadata(",
        f"                plantTypeId: {definition.plant_type_id},",
        f"                canonicalName: {_csharp_string(definition.canonical_name)},",
        f"                aliases: {_render_aliases(definition.aliases)},",
        f"                fallbackCost: {definition.fallback_cost},",
        f"                fallbackCooldownSeconds: {_csharp_float(definition.fallback_cooldown)},",
        f"                category: {_csharp_string(definition.category)},",
        f"                role: {_csharp_string(definition.role)},",
        f"                enabledForTraining: {str(definition.enabled_for_training).lower()},",
        f"                bridgeFallbackEnabled: {str(definition.bridge_fallback_enabled).lower()}),",
    ]


def _name_id_pairs(registry: PlantRegistry) -> list[tuple[str, int]]:
    pairs: dict[str, int] = {}
    for definition in sorted(registry.plants, key=lambda item: item.plant_type_id):
        for name in (definition.canonical_name, *definition.aliases):
            key = normalize_plant_name(name)
            if not key:
                continue
            existing = pairs.get(key)
            if existing is not None and existing != definition.plant_type_id:
                raise ValueError(
                    f"canonical registry name {name!r} resolves to both {existing} and {definition.plant_type_id}"
                )
            pairs[key] = definition.plant_type_id
    return sorted(pairs.items(), key=lambda item: (-len(item[0]), item[0], item[1]))


def _render_name_matchers(registry: PlantRegistry) -> list[str]:
    # Text probes contain full hierarchy paths and reward copy.  Ignore very
    # short aliases so words such as "pea", "sun", or "nut" cannot make an
    # unrelated UI label look like an unlock.
    pairs = [(key, plant_type_id) for key, plant_type_id in _name_id_pairs(registry) if len(key) >= 5]
    return [f'        ({_csharp_string(key)}, {plant_type_id}),' for key, plant_type_id in pairs]


def render_bridge_registry(registry: PlantRegistry) -> str:
    if not registry.plants:
        raise ValueError(f"canonical plant registry is empty: {registry.source_path}")

    lines = [
        "// <auto-generated>",
        "// Generated by scripts/generate_bridge_registry.py from configs/plant_registry.json.",
        "// Runtime CardUI metadata remains authoritative; these values are fallbacks only.",
        "// </auto-generated>",
        "#nullable enable",
        "using System;",
        "using System.Collections.Generic;",
        "using System.Globalization;",
        "using System.Text;",
        "",
        "namespace PvZRLBridge;",
        "",
        "internal sealed class GeneratedPlantMetadata",
        "{",
        "    public GeneratedPlantMetadata(",
        "        int plantTypeId,",
        "        string canonicalName,",
        "        IReadOnlyList<string> aliases,",
        "        int fallbackCost,",
        "        float fallbackCooldownSeconds,",
        "        string category,",
        "        string role,",
        "        bool enabledForTraining,",
        "        bool bridgeFallbackEnabled)",
        "    {",
        "        PlantTypeId = plantTypeId;",
        "        CanonicalName = canonicalName;",
        "        Aliases = aliases;",
        "        FallbackCost = fallbackCost;",
        "        FallbackCooldownSeconds = fallbackCooldownSeconds;",
        "        Category = category;",
        "        Role = role;",
        "        EnabledForTraining = enabledForTraining;",
        "        BridgeFallbackEnabled = bridgeFallbackEnabled;",
        "    }",
        "",
        "    public int PlantTypeId { get; }",
        "    public string CanonicalName { get; }",
        "    public IReadOnlyList<string> Aliases { get; }",
        "    public int FallbackCost { get; }",
        "    public float FallbackCooldownSeconds { get; }",
        "    public string Category { get; }",
        "    public string Role { get; }",
        "    public bool EnabledForTraining { get; }",
        "    public bool BridgeFallbackEnabled { get; }",
        "}",
        "",
        "internal static class GeneratedPlantRegistry",
        "{",
        f"    public const string SourceSha256 = {_csharp_string(registry.content_sha256)};",
        "",
        "    private static readonly IReadOnlyDictionary<int, GeneratedPlantMetadata> ById =",
        "        new Dictionary<int, GeneratedPlantMetadata>",
        "        {",
    ]
    for definition in sorted(registry.plants, key=lambda item: item.plant_type_id):
        lines.extend(_render_entry(definition))
    lines.extend(
        [
            "        };",
            "",
            "    private static readonly IReadOnlyDictionary<string, int> ByNormalizedName =",
            "        new Dictionary<string, int>(StringComparer.Ordinal)",
            "        {",
        ]
    )
    for key, plant_type_id in _name_id_pairs(registry):
        lines.append(f"            [{_csharp_string(key)}] = {plant_type_id},")
    lines.extend(
        [
            "        };",
            "",
            "    private static readonly (string Key, int PlantTypeId)[] TextMatchers =",
            "        new[]",
            "        {",
        ]
    )
    lines.extend(_render_name_matchers(registry))
    lines.extend(
        [
            "        };",
            "",
            "    public static int Count => ById.Count;",
            "",
            "    public static bool TryGet(int plantTypeId, out GeneratedPlantMetadata metadata)",
            "    {",
            "        if (ById.TryGetValue(plantTypeId, out var resolved))",
            "        {",
            "            metadata = resolved;",
            "            return true;",
            "        }",
            "",
            "        metadata = null!;",
            "        return false;",
            "    }",
            "",
            "    public static bool TryResolvePlantTypeId(string? value, out int plantTypeId)",
            "    {",
            "        var key = NormalizeName(value);",
            "        if (string.IsNullOrWhiteSpace(key))",
            "        {",
            "            plantTypeId = -1;",
            "            return false;",
            "        }",
            "",
            "        return ByNormalizedName.TryGetValue(key, out plantTypeId);",
            "    }",
            "",
            "    public static bool TryResolvePlantTypeIdFromText(string? value, out int plantTypeId)",
            "    {",
            "        var normalized = NormalizeName(value);",
            "        if (string.IsNullOrWhiteSpace(normalized))",
            "        {",
            "            plantTypeId = -1;",
            "            return false;",
            "        }",
            "",
            "        foreach (var matcher in TextMatchers)",
            "        {",
            "            if (normalized.Contains(matcher.Key, StringComparison.Ordinal))",
            "            {",
            "                plantTypeId = matcher.PlantTypeId;",
            "                return true;",
            "            }",
            "        }",
            "",
            "        plantTypeId = -1;",
            "        return false;",
            "    }",
            "",
            "    private static string NormalizeName(string? value)",
            "    {",
            "        if (string.IsNullOrWhiteSpace(value))",
            "        {",
            "            return string.Empty;",
            "        }",
            "",
            "        var builder = new StringBuilder(value.Length);",
            "        foreach (var character in value)",
            "        {",
            "            if (char.IsLetterOrDigit(character))",
            "            {",
            "                builder.Append(char.ToLowerInvariant(character));",
            "            }",
            "        }",
            "",
            "        return builder.ToString();",
            "    }",
            "",
            "    public static bool TryGetBridgeFallbackCost(int plantTypeId, out int cost)",
            "    {",
            "        if (TryGet(plantTypeId, out var metadata) && metadata.BridgeFallbackEnabled)",
            "        {",
            "            cost = metadata.FallbackCost;",
            "            return true;",
            "        }",
            "",
            "        cost = 0;",
            "        return false;",
            "    }",
            "",
            "    public static string ResolveCanonicalNameFallback(int plantTypeId, string runtimeName)",
            "    {",
            "        var numericName = plantTypeId.ToString(CultureInfo.InvariantCulture);",
            "        if (!string.IsNullOrWhiteSpace(runtimeName) &&",
            "            !string.Equals(runtimeName, numericName, StringComparison.Ordinal))",
            "        {",
            "            return runtimeName;",
            "        }",
            "",
            "        return TryGet(plantTypeId, out var metadata) ? metadata.CanonicalName : runtimeName;",
            "    }",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def generate(registry_path: Path, output_path: Path, *, check: bool) -> bool:
    registry = get_plant_registry(registry_path)
    expected = render_bridge_registry(registry)
    existing = output_path.read_text(encoding="utf-8") if output_path.exists() else None
    if check:
        if existing != expected:
            print(f"generated bridge registry is stale: {output_path}", file=sys.stderr)
            return False
        return True
    if existing != expected:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(expected, encoding="utf-8", newline="\n")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--registry", type=Path, default=DEFAULT_PLANT_REGISTRY_PATH)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT_PATH)
    parser.add_argument("--check", action="store_true", help="Fail instead of writing when output is stale.")
    args = parser.parse_args()
    return 0 if generate(args.registry.resolve(), args.output.resolve(), check=bool(args.check)) else 1


if __name__ == "__main__":
    raise SystemExit(main())
